project:
  type: website

website:
  title: "Inspect SWE"
  navbar:
    search: true
    left:
      - text: Home
        href: index.qmd
      - text: Agents
        menu:
           - href: claude_code.qmd
           - href: codex_cli.qmd
           - href: gemini_cli.qmd
           - href: mini_swe_agent.qmd
    right:
      - text: Changelog
        href: CHANGELOG.md
      - icon: github
        href: https://github.com/meridianlabs-ai/inspect_swe
        aria-label: GitHub
  sidebar:
     - contents:
        - text: Getting Started
          href: index.qmd
        - section: Agents
          contents:
            - href: claude_code.qmd
            - href: codex_cli.qmd
            - href: gemini_cli.qmd
            - href: mini_swe_agent.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



